apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: popeye-backend-config
  namespace: staging
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false