apiVersion: apps/v1
kind: Deployment
metadata:
  name: popeye-celery-worker
  labels:
    app: popeye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: popeye-celery-worker
  template:
    metadata:
      annotations:
        version: latest
      labels:
        app: popeye-celery-worker
    spec:
      imagePullSecrets:
      - name: unnotech
      containers:
      - name: popeye-celery-worker
        image: nickest11/popeye:master
        imagePullPolicy: Always
        command: ["celery"]
        args: ["-A", "popeye", "worker", "-l", "debug", "-Q", "celery", "-n", "celery@%h"]
        resources: {}
        envFrom:
        - configMapRef:
            name: popeye-django
        - configMapRef:
            name: popeye-rabbitmq
        - configMapRef:
            name: popeye-postgres
        - secretRef:
            name: popeye-django
        - secretRef:
            name: popeye-postgres
        - secretRef:
            name: popeye-rabbitmq
        - secretRef:
            name: popeye-celery
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=$(CLOUDSQL_INSTANCE)=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        envFrom:
        - configMapRef:
            name: popeye-cloudsql-instance
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-db-credentials